# Generated by Django 2.2.6 on 2019-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='puser',
        ),
    ]
