# Generated by Django 2.2.6 on 2019-10-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20191008_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='puser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cr_date',
        ),
    ]
