# Generated by Django 2.2.6 on 2019-10-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20191008_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
