# Generated by Django 2.2.6 on 2019-10-09 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_profile_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mark_10',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MinValueValidator(100))]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mark_12',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MinValueValidator(100))]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mark_aggr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, django.core.validators.MinValueValidator(100))]),
        ),
    ]
