# Generated by Django 2.2.6 on 2019-10-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20191009_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='userProfile',
        ),
    ]
