# Generated by Django 2.2.6 on 2019-10-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20191009_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userProfile',
            new_name='user',
        ),
    ]
